### PR TITLE
Switch to the new API for `marking as required` the fields for some resources

### LINKED ISSUE #472: [Bug]: Creation of compute Instances (and others) fails with `SetNew only operates on computed keys`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* compute.gcp.upbound.io/v1beta1 - Instance
* cloudscheduler.gcp.upbound.io/v1beta1 - Job

### Resource MRs required to reproduce the bug

examples/compute/instance.yaml
examples/cloudscheduler/job.yaml

### Steps to Reproduce

Apply examples/compute/instance.yaml (or examples/cloudscheduler/job.yaml)

### What happened?

External resource was not created, reconciliation fails with an error from terraform:
`observe failed: cannot compute the instance diff: failed to get *terraform.InstanceDiff: SetNew only operates on computed keys - zone is not one`
(For Job it's `... - region is not one`)

### Relevant Error Output Snippet

_No response_

### Crossplane Version

1.15.0

### Provider Version

1.0.0

### Kubernetes Version

_No response_

### Kubernetes Distribution

_No response_

### Additional Info

The failing calls to SetNew appear to have been introduced in https://github.com/GoogleCloudPlatform/magic-modules/pull/8569

### PR DESCRIPTION
**Pull request by sergenyalcin**
### Description of your changes

This PR switches to the [new API for `marking as required`](https://github.com/sergenyalcin/upjet/blob/845dbf6b1b11cdcc329cea004fc29e2d23c5343b/pkg/config/common.go#L129) the fields. The new API will mark as required the fields during the generation without any native resource schema change. For mor details of this new API please see this [PR](https://github.com/crossplane/upjet/pull/381). The base strategies we decided in this PR:
- Upjet's `config.MarkAsRequired` still modifies the native schema (no change in its implementation) but it's now deprecated in favor of `config.Resource.MarkAsRequired`.
- Other clients of the config.MarkAsRequired are not updated to use the new config.Resource.MarkAsRequired in this PR because the config.MarkAsRequired modifies Terraform's runtime behavior (potentially also outside the context of the defaulting CustomizeDiff functions) by manipulating the native schema, and so we would like to test those resources which are updated to use the new config.Resource.MarkAsRequired. So it's a larger effort to transition all the clients of the config.MarkAsRequired and we limit the scope of this PR by only updating the configurations of the following resources.

Fixes #472 

The root cause of #472 is native schema change of the `zone` and `region` field. The new `CustomizeDiff` functions of the underlying provider, [DefaultProviderRegion](https://github.com/hashicorp/terraform-provider-google/blob/a9e2f2c89f14496301cac609f3e8c71fc9558a2a/google/tpgresource/utils.go#L791) and [DefaultProviderZone](https://github.com/hashicorp/terraform-provider-google/blob/a9e2f2c89f14496301cac609f3e8c71fc9558a2a/google/tpgresource/utils.go#L809), checks the `Computed` fields of the resource schemas and gives some decisions according to the values. At this point, because of manipulating the resource schema (what we must not do), we observe this issue. By this change, we will revert the schema changes for the affected resources. The affected resources were determined according to the two following rules:

- The resource configuration should contain schema manipulation via `MarkAsRequired` for `zone` or `region` fields.
- The native schema of resource should contain at least on of the mentioned `CustomizeDiff` functions.

Switched to the new API for the following resources:

1. `Environment.composer`
2. `Job.cloudscheduler`
3. `Autoscaler.compute`
4. `Instance.compute`
5. `InstanceGroup.compute`
6. `InstanceGroupManager.compute`
7. `NetworkEndpointGroup.compute`
8. `ResourcePolicy.compute`
9. `TargetPool.compute`
10. `RegionInstanceGroupManager.compute`
11. `RegionAutoScaler.compute`
12. `ServiceAttachment.compute`
13. `EntryGroup.datacatalog`

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

1. `Instance.compute`: https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/8343310426
2. `Job.cloudscheduler`: https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/8343708323
3. `InstanceGroup.compute`: https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/8343704491
4. `ResourcePolicy.compute`: https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/8343851010
5. `EntryGroup.datacatalog`: https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/8343873861
6. `RegionAutoScaler.compute`: https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/8344124389
7. `NetworkEndpointGroup.compute`: https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/8344103249
8. `RegionInstanceGroupManager.compute`: https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/8344548614
9. `ServiceAttachment.compute`: Manually (because of manual intervention need)
10. `TargetPool.compute`: https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/8344649274
11. `Autoscaler.compute`: https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/8345034404
12. `InstanceGroupManager.compute`: https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/8345034404
13. `Environment.composer`: Manually (because of service account permission issues)

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/instance.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/instancegroup.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/cloudscheduler/job.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/composer/environment.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/autoscaler.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/resourcepolicy.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/datacatalog/entrygroup.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/networkendpointgroup.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/regionautoscaler.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/composer/environment.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/autoscaler.yaml"

File: config/compute/config.go [hunk 1]
```diff
@@ -399,10 +399,6 @@ func Configure(p *config.Provider) { //nolint: gocyclo
 		config.MarkAsRequired(r.TerraformResource, "region")
 	})
 
-	p.AddResourceConfigurator("google_compute_region_per_instance_config", func(r *config.Resource) {
```
Comment (ulucinar) [inline config/compute/config.go:402]: Does this resource no longer exist? Is this unnecessary?

File: examples/composer/environment.yaml [hunk 2]
```diff
@@ -13,9 +13,3 @@ metadata:
 spec:
   forProvider:
     region: us-east1
-    config:
```
Comment (ulucinar) [inline examples/composer/environment.yaml:16]: Why did we have to remove this configuration?

**Comment by ulucinar** [comment]
Hi @sergenyalcin,
Let's also discuss in the PR description the strategy we decided on in https://github.com/crossplane/upjet/pull/381:
a. Upjet's `config.MarkAsRequired` still modifies the native schema (no change in its implementation) but it's now deprecated in favor of `config.Resource.MarkAsRequired`. 
b. This PR only updates & tests those resources whose configuration uses `config.MarkAsRequired` and their corresponding Terraform resources employ the [new project and zone defaulting CustomizeDiffs](https://github.com/crossplane-contrib/provider-upjet-gcp/issues/472#issuecomment-2007558562) -> This is already mentioned in the PR description.
c. Other clients of the `config.MarkAsRequired` are not updated to use the new `config.Resource.MarkAsRequired` in this PR because the `config.MarkAsRequired` modifies Terraform's runtime behavior (potentially also outside the context of the defaulting `CustomizeDiff` functions) by manipulating the native schema, and so we would like to test those resources which are updated to use the new `config.Resource.MarkAsRequired`. So it's a larger effort to transition all the clients of the `config.MarkAsRequired` and we limit the scope of this PR by only updating the configurations of the resources in [b].

File: config/compute/config.go (hunk 1 above)
Comment (sergenyalcin) [reply config/compute/config.go:402]: I deleted this statement because this configuration does not have an effect. The `region` field is generated as a `Reference` field, and we mark the reference fields as `Optional` regardless of their status in the scheme. Also, as can be seen, even though the configuration was deleted, no diff occurred after generation. This shows that this configuration block has no function.

File: examples/composer/environment.yaml (hunk 2 above)
Comment (sergenyalcin) [reply examples/composer/environment.yaml:16]: I checked the registry documentation, and this usage is no longer valid. Also, there was a basic usage in the example of registry. I changed this example to a basic one to avoid leading the user to the view that the config block is required. In this context, we can consider providing different example manifests for different purposes and use cases, which we discussed before.

File: config/compute/config.go (hunk 1 above)
Comment (ulucinar) [reply config/compute/config.go:402]: Thank you for the explanation.

**Review by ulucinar — APPROVED** [review]
Thanks @sergenyalcin, lgtm.
